project_id = "vegtxitejztnhnsobzqi"

[functions.send-weekly-notification]
verify_jwt = false

[functions.check-achievements]
verify_jwt = false

[functions.approve-user]
verify_jwt = true

[functions.calculate-contest-rankings]
verify_jwt = false
